version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:

  python:
    container_name: python
    image: osirixfoundation/c-move:master
    restart: on-failure
    #command: 1999-11-10 2006-12-31 arc1 11112 DCM4CHEE TESTCMOVE
    command: ["1999-11-10", "2006-12-31", "arc1", "11112", "DCM4CHEE", "TESTCMOVE"]
    #command: python3 combo.py
    networks:
      - pacs_network


networks:
  pacs_network:
    external:
      name: pacs_network
