language: minimal

notifications:
  email: false

script:
   - docker build -t osirixfoundation/c-move:$TRAVIS_BRANCH .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
   - docker push osirixfoundation/c-move:$TRAVIS_BRANCH
